# Site settings
title: Lind Docs
author:
  name: Ruchir Joshi
  email: ruchirjoshi@nyu.edu
description: "Documentaiton for the Lind Project"

# Build settings
remote_theme: jekyll/minima

# GitHub Pages settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge



# Exclude files and folders
exclude:
  - node_modules
  - vendor
